version: "3.8"
services:
    www:
        build: .
        ports:
            - 8081-8090:80
        volumes:
            - ./www:/var/www/html/
        depends_on:
            - db
        networks:
            - default
    lb:
        image: dockercloud/haproxy
        ports:
            - 80:80
            - 1936:1936
        links:
            - www
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
    db:
        image: mariadb:10
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: dbapp
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./db:/docker-entrypoint-initdb.d
            - persistent:/var/lib/mysql
        networks:
            - default
    redis:
        image: redis:latest

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        depends_on:
            - db
        ports:
            - 9090:80
        environment:
            MYSQL_USER: root
            MYSQL_PASSWORD: root
            MYSQL_ROOT_PASSWORD: root
volumes:
    persistent:
