version: '3.8'
services:
  www:
    image: php:7.4-apache
    volumes:
     - ./www:/var/www/html
    links:
     - redis

  redis:
    image: redis
    
  haproxy:
    image: dockercloud/haproxy
    links:
     - www
    ports:
     - 80:80
     - 1936:1936
    environment:
     - STATS_AUTH="admin:password"
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
